Json schema
RMI-PACTA/actions pull request #106
Opened 2024-08-21 08:17 UTC by AlexAxthelm

2024-08-22 07:56 UTC, jdhoffa requested changes
A few typos, and one comment/ question on the `config.json` implementation

2024-08-22 07:56 UTC, jdhoffa commented on actions/json-schema/check-docs/README.md
> +INputs are the same as the `render-docs` action, and are passed through to that action.
```suggestion
Inputs are the same as the `render-docs` action and are passed through to that action.
```

2024-08-22 07:56 UTC, jdhoffa commented on actions/json-schema/render-docs/Dockerfile
neat!

2024-08-22 07:56 UTC, jdhoffa commented on actions/json-schema/render-docs/action.yml
> +description: 'Render JSON Schema docs usin json-schema-for-humans'
```suggestion
description: 'Render JSON Schema docs using json-schema-for-humans'
```

2024-08-22 07:56 UTC, jdhoffa commented on actions/json-schema/render-docs/config.json
As I understand it, this `config.json` is used to configure the resultant documentation, correct? 
Is it possible that this might conflict with the configuration that a user of this action might have locally? 

I can imagine the following situation where: 
* User (of action) has a `config.json` set-up in their local repo to configure how documentation is set-up
* User renders docs locally
* User implements the `check-docs` action (which depends on the `render-docs` action)
* `check-docs` fails since local and action version of rendered docs have inconsistent `config.json`

Do you think that is a reasonable concern, or do I misunderstand something?

2024-08-22 08:19 UTC, jdhoffa commented on actions/json-schema/render-docs/config.json
Is it likely or worth doing that? 
I don't use JSON/ JSON-schema in practice frequently, so I can't say, but I'm just trying to foresee any potential annoying future bugs. 

If you think I'm being paranoid then no problem

2024-08-27 13:03 UTC, AlexAxthelm commented on actions/json-schema/render-docs/config.json
Maybe paranoid, but not too hard a change. See https://github.com/RMI-PACTA/workflow.pacta/pull/95 for an example.

Prior to changes (passing): https://github.com/RMI-PACTA/workflow.pacta/actions/runs/10576553025/job/29302584442
Adding new config but not rendered docs (failing) https://github.com/RMI-PACTA/workflow.pacta/actions/runs/10578407548/job/29308460733
Adding config and docs (Passing) https://github.com/RMI-PACTA/workflow.pacta/actions/runs/10578458357/job/29308619989?pr=95

2024-09-03 07:36 UTC, jdhoffa approved these changes

2024-09-03 08:04 UTC, merged